version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: India/Kolkata
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: India/kolkata
  open-pull-requests-limit: 10
  target-branch: master
  allow:
  - dependency-type: direct
  - dependency-type: indirect
